name: web_network
description: "Web-specific network implementations and overrides"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
    
  network_interface:
    path: ../network_interface
  models:
    path: ../../core/models
  di:
    path: ../../core/di
    
  # Base networking (inherits from dio_network)
  dio: ^5.4.3+1
  web_socket_channel: ^3.0.3
  
  # Web-specific networking
  # dart:html is automatically available on web
  
  # DI
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.12
  injectable_generator: ^2.6.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^9.0.0
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
