name: memory_storage
description: "In-memory storage for testing"
version: 1.0.0
publish_to: 'none' 

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  storage_interface:
    path: ../storage_interface
  models:
    path: ../../core/models
  di:
    path: ../../core/di
    
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  injectable_generator: ^2.6.1
  lints: ^6.0.0
  test: ^1.25.6
  very_good_analysis: ^9.0.0
