name: storage_interface
description: "Storage abstractions and contracts"
publish_to: none

environment:
  sdk: ^3.13.0
resolution: workspace

dependencies:
  interfaces:
    path: ../../core/interfaces
  models:
    path: ../../core/models

dev_dependencies:
  test: ^1.31.1
  very_good_analysis: ^10.2.0
  lints: ^6.1.0
