name: interfaces
description: "Abstract contracts and interfaces"

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  # Minimal dependencies for interfaces
  meta: ^1.12.0

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^9.0.0
  lints: ^6.0.0
