name: ui
description: "Reusable UI components and themes"
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  interfaces:
    path: ../core/interfaces
  models:
    path: ../core/models
  di:
    path: ../core/di
    
  # Forms
  reactive_forms: ^18.1.1
  reactive_forms_annotations: ^8.0.1
  
  # Essential UI
  flutter_animate: ^4.5.0           
  cached_network_image: ^3.3.1      
  flutter_svg: ^2.0.10+1            
  shimmer: ^3.0.0                   
  
  # Interactive Widgets
  flutter_slidable: ^4.0.1         
  expansion_tile_card: ^3.0.0        
  flutter_speed_dial: ^7.0.0       
  flutter_typeahead: ^5.2.0        
  flutter_rating_bar: ^4.0.1       
  flutter_colorpicker: ^1.1.0      
  
  # Layout & Structure
  flutter_staggered_grid_view: ^0.7.0 
  flutter_sticky_header: ^0.8.0    
  super_sliver_list: ^0.4.1        
  
  # Loading & Progress
  flutter_spinkit: ^5.2.1          
  
  # Media & Graphics
  photo_view: ^0.15.0               
  image_picker: ^1.1.2             
  
  # Charts & Data Viz
  fl_chart: ^1.1.0                 
  
  # Text & Input
  animated_text_kit: ^4.2.2        
  flutter_markdown: ^0.7.3+1       
  flutter_chips_input: ^2.0.0      
  pin_code_fields: ^8.0.1          
  
  # Overlays & Modals
  flutter_portal: ^1.1.4           
  modal_bottom_sheet: ^3.0.0       
  awesome_dialog: ^3.2.1           
  
  # Navigation Helpers
  persistent_bottom_nav_bar_v2: ^6.1.0 
  salomon_bottom_bar: ^3.3.2       
  
  # Animations
  lottie: ^3.1.2                    
  rive: ^0.13.1                     
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.12
  reactive_forms_generator: ^6.1.0
  flutter_lints: ^6.0.0
  
  # Testing
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true