name: models
description: "Shared data models and DTOs"
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  interfaces:
    path: ../interfaces
    
  # Serialization
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0

dev_dependencies:
  freezed: ^3.0.6
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  test: ^1.25.6
  very_good_analysis: ^9.0.0
  lints: ^6.0.0
