// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    games,
    platformGames,
    gameCollections,
    households,
    householdMembers,
    syncQueue,
    platformGamesGameIdIdx,
    gameCollectionsUserIdx,
    gameCollectionsUserPgameMediumUniqueIdx,
    householdMembersUserIdx,
    householdMembersHouseholdUserUniqueIdx,
    syncQueueStatusIdx,
  ];
  late final Shape0 games = Shape0(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 platformGames = Shape1(
    source: i0.VersionedTable(
      entityName: 'platform_games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_32,
        _column_33,
        _column_34,
        _column_7,
        _column_8,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_4,
        _column_5,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 gameCollections = Shape2(
    source: i0.VersionedTable(
      entityName: 'game_collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 households = Shape3(
    source: i0.VersionedTable(
      entityName: 'households',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_55,
        _column_3,
        _column_4,
        _column_53,
        _column_54,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 householdMembers = Shape4(
    source: i0.VersionedTable(
      entityName: 'household_members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_41,
        _column_56,
        _column_57,
        _column_58,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 syncQueue = Shape5(
    source: i0.VersionedTable(
      entityName: 'sync_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_30,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index platformGamesGameIdIdx = i1.Index(
    'platform_games_game_id_idx',
    'CREATE INDEX platform_games_game_id_idx ON platform_games (game_id)',
  );
  final i1.Index gameCollectionsUserIdx = i1.Index(
    'game_collections_user_idx',
    'CREATE INDEX game_collections_user_idx ON game_collections (user_id)',
  );
  final i1.Index gameCollectionsUserPgameMediumUniqueIdx = i1.Index(
    'game_collections_user_pgame_medium_unique_idx',
    'CREATE UNIQUE INDEX game_collections_user_pgame_medium_unique_idx ON game_collections (user_id, platform_game_id, medium) WHERE deleted_at IS NULL',
  );
  final i1.Index householdMembersUserIdx = i1.Index(
    'household_members_user_idx',
    'CREATE INDEX household_members_user_idx ON household_members (user_id)',
  );
  final i1.Index householdMembersHouseholdUserUniqueIdx = i1.Index(
    'household_members_household_user_unique_idx',
    'CREATE UNIQUE INDEX household_members_household_user_unique_idx ON household_members (household_id, user_id)',
  );
  final i1.Index syncQueueStatusIdx = i1.Index(
    'sync_queue_status_idx',
    'CREATE INDEX sync_queue_status_idx ON sync_queue (status, created_at)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get subtitle =>
      columnsByName['subtitle']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get image =>
      columnsByName['image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnail =>
      columnsByName['thumbnail']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get publishYear =>
      columnsByName['publish_year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPlayers =>
      columnsByName['min_players']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxPlayers =>
      columnsByName['max_players']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playingTime =>
      columnsByName['playing_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPlayTime =>
      columnsByName['min_play_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get minPlayTimeMeasure =>
      columnsByName['min_play_time_measure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get maxPlayTime =>
      columnsByName['max_play_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get maxPlayTimeMeasure =>
      columnsByName['max_play_time_measure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get minAge =>
      columnsByName['min_age']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get complexity =>
      columnsByName['complexity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get contentType =>
      columnsByName['content_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalPlayCount =>
      columnsByName['total_play_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get averageRating =>
      columnsByName['average_rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get bayesRating =>
      columnsByName['bayes_rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get ratingsCount =>
      columnsByName['ratings_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ownedByCount =>
      columnsByName['owned_by_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get categoriesJson =>
      columnsByName['categories_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mechanicsJson =>
      columnsByName['mechanics_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get designersJson =>
      columnsByName['designers_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publishersJson =>
      columnsByName['publishers_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tagsJson =>
      columnsByName['tags_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get visibility =>
      columnsByName['visibility']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdById =>
      columnsByName['created_by_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'subtitle',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'image',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumbnail',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'publish_year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'min_players',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'max_players',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'playing_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'min_play_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'min_play_time_measure',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'max_play_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'max_play_time_measure',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'min_age',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'complexity',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'BaseGame\'',
      defaultValue: const i1.CustomExpression('\'BaseGame\''),
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_play_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<double> _column_18(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'average_rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_19(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'bayes_rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ratings_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'owned_by_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'categories_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mechanics_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'designers_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'publishers_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tags_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'visibility',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'Public\'',
      defaultValue: const i1.CustomExpression('\'Public\''),
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_by_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gameId =>
      columnsByName['game_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get platformId =>
      columnsByName['platform_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get platformName =>
      columnsByName['platform_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get minPlayers =>
      columnsByName['min_players']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxPlayers =>
      columnsByName['max_players']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPlayTime =>
      columnsByName['min_play_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get minPlayTimeMeasure =>
      columnsByName['min_play_time_measure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get maxPlayTime =>
      columnsByName['max_play_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get maxPlayTimeMeasure =>
      columnsByName['max_play_time_measure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get image =>
      columnsByName['image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnail =>
      columnsByName['thumbnail']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get supportsSolo =>
      columnsByName['supports_solo']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get supportsLocal =>
      columnsByName['supports_local']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get supportsOnline =>
      columnsByName['supports_online']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hasAsyncPlay =>
      columnsByName['has_async_play']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hasRealtime =>
      columnsByName['has_realtime']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get hasTutorial =>
      columnsByName['has_tutorial']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'game_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES games(id)',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'supports_solo',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (supports_solo IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'supports_local',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (supports_local IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'supports_online',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (supports_online IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'has_async_play',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (has_async_play IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'has_realtime',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (has_realtime IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'has_tutorial',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (has_tutorial IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get platformGameId =>
      columnsByName['platform_game_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get medium =>
      columnsByName['medium']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get releaseId =>
      columnsByName['release_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playCount =>
      columnsByName['play_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get playAgain =>
      columnsByName['play_again']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get favorite =>
      columnsByName['favorite']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get comment =>
      columnsByName['comment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastPlayed =>
      columnsByName['last_played']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastUpdated =>
      columnsByName['last_updated']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDirty =>
      columnsByName['is_dirty']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isLocalOnly =>
      columnsByName['is_local_only']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform_game_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES platform_games(id)',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'medium',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'release_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'play_count',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'play_again',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (play_again IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'favorite',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (favorite IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'comment',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_played',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_updated',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_dirty',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_dirty IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_local_only',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_local_only IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get image =>
      columnsByName['image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isDirty =>
      columnsByName['is_dirty']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isLocalOnly =>
      columnsByName['is_local_only']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get householdId =>
      columnsByName['household_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get showAllGames =>
      columnsByName['show_all_games']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get roleName =>
      columnsByName['role_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'household_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES households(id)',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'show_all_games',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (show_all_games IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'pending\'',
      defaultValue: const i1.CustomExpression('\'pending\''),
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'retry_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    games,
    platformGames,
    gameCollections,
    households,
    householdMembers,
    syncQueue,
    platformGamesGameIdIdx,
    gameCollectionsUserIdx,
    gameCollectionsUserPgameMediumUniqueIdx,
    householdMembersUserIdx,
    householdMembersHouseholdUserUniqueIdx,
    syncQueueUserStatusIdx,
  ];
  late final Shape0 games = Shape0(
    source: i0.VersionedTable(
      entityName: 'games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 platformGames = Shape1(
    source: i0.VersionedTable(
      entityName: 'platform_games',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_32,
        _column_33,
        _column_34,
        _column_7,
        _column_8,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_4,
        _column_5,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 gameCollections = Shape2(
    source: i0.VersionedTable(
      entityName: 'game_collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 households = Shape3(
    source: i0.VersionedTable(
      entityName: 'households',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_55,
        _column_3,
        _column_4,
        _column_53,
        _column_54,
        _column_29,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 householdMembers = Shape4(
    source: i0.VersionedTable(
      entityName: 'household_members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_41,
        _column_56,
        _column_57,
        _column_58,
        _column_30,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 syncQueue = Shape6(
    source: i0.VersionedTable(
      entityName: 'sync_queue',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_41,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_30,
        _column_63,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index platformGamesGameIdIdx = i1.Index(
    'platform_games_game_id_idx',
    'CREATE INDEX platform_games_game_id_idx ON platform_games (game_id)',
  );
  final i1.Index gameCollectionsUserIdx = i1.Index(
    'game_collections_user_idx',
    'CREATE INDEX game_collections_user_idx ON game_collections (user_id)',
  );
  final i1.Index gameCollectionsUserPgameMediumUniqueIdx = i1.Index(
    'game_collections_user_pgame_medium_unique_idx',
    'CREATE UNIQUE INDEX game_collections_user_pgame_medium_unique_idx ON game_collections (user_id, platform_game_id, medium) WHERE deleted_at IS NULL',
  );
  final i1.Index householdMembersUserIdx = i1.Index(
    'household_members_user_idx',
    'CREATE INDEX household_members_user_idx ON household_members (user_id)',
  );
  final i1.Index householdMembersHouseholdUserUniqueIdx = i1.Index(
    'household_members_household_user_unique_idx',
    'CREATE UNIQUE INDEX household_members_household_user_unique_idx ON household_members (household_id, user_id)',
  );
  final i1.Index syncQueueUserStatusIdx = i1.Index(
    'sync_queue_user_status_idx',
    'CREATE INDEX sync_queue_user_status_idx ON sync_queue (user_id, status, created_at)',
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get retryCount =>
      columnsByName['retry_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastError =>
      columnsByName['last_error']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastAttemptAt =>
      columnsByName['last_attempt_at']! as i1.GeneratedColumn<String>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
